### ISSUE TITLE
Wrong alg?

### ISSUE THREAD

**Issue by Berkmann18** [Roman-/zbll-trainer#8]
The scramble for the case H-FBFB, C/A seems wrong:
`L' U' L U2 F2 U F2 U F2 U2 F2 L' U L` as it leaves a ZBLS.

**Comment by Roman-** [comment]
> L' U' L U2 F2 U F2 U F2 U2 F2 L' U L

Hey. This scramble is for the case H-FBFB, A/A. Not for H-FBFB, C/A.
https://github.com/Roman-/zbll-trainer/blob/master/scripts/casesmap.js#L180

**Comment by Berkmann18** [comment]
@Roman- You're right.
