### ISSUE TITLE
Naming presets with single or double quotes corrupts them

### ISSUE THREAD

**Issue by Edify-Multitude** [Roman-/zbll-trainer#9]
A preset saved with a single or a double quote in its name can't be neither loaded nor deleted.

**Comment by Roman-** [comment]
I think there's no need for preset names with quotes and other special chars in it. I will resolve this by restricting the names of the preset.

**Comment by Roman-** [comment]
Made hotfix that silently replaces special characters ' " \\ with space and then trims the preset name. https://github.com/Roman-/zbll-trainer/commit/a2307464cc7d2a76578905bfc99539beb319afbe
